=== mymmsc/hotwheel/hotwheel-mybatis/src/main/java/org/hotwheel/mybatis/builder/xml/hotwheel-mybatis-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2009-2016 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!ELEMENT hotwheel-mybatis (properties?, environments?, mappers?)>

<!ELEMENT properties (property*)>
<!ATTLIST properties
        resource CDATA #IMPLIED
        url CDATA #IMPLIED
        >

<!ELEMENT property EMPTY>
<!ATTLIST property
        name CDATA #REQUIRED
        value CDATA #REQUIRED
        >

<!ELEMENT environments (environment+)>
<!ATTLIST environments
        default CDATA #REQUIRED
        >

<!ELEMENT environment (transactionManager,dataSource)>
<!ATTLIST environment
        id CDATA #REQUIRED
        >

<!ELEMENT transactionManager (property*)>
<!ATTLIST transactionManager
        type CDATA #REQUIRED
        >

<!ELEMENT dataSource (property*)>
<!ATTLIST dataSource
        id CDATA #REQUIRED
        class CDATA #REQUIRED
        destroy-method CDATA #REQUIRED
        >

<!ELEMENT mappers (mapper*,package*)>

<!ELEMENT mapper EMPTY>
<!ATTLIST mapper
        resource CDATA #IMPLIED
        url CDATA #IMPLIED
        class CDATA #IMPLIED
        >

<!ELEMENT package EMPTY>
<!ATTLIST package
        name CDATA #REQUIRED
        >

=== mymmsc/hotwheel/hotwheel-test/src/main/resources/mybatis/hotwheel-mybatis.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE hotwheel-mybatis
        PUBLIC "-//hotwheel.org//DTD Config 3.0//EN"
        "http://hotwheel.org/dtd/hotwheel-mybatis-config.dtd">

<hotwheel-mybatis>

    <properties resource="mysql-jdbc.properties"/>

    <environments default="development">
        <environment id="development">
            <transactionManager type="JDBC"/>
            <dataSource id="cuishou" class="org.hotwheel.mybatis.HotWheelDataSourceFactory" destroy-method="close">
                <property name="driverClassName" value="${cuishou.driver}" />
                <property name="url" value="${cuishou.url}" />
                <property name="username" value="${cuishou.username}" />
                <property name="password" value="${cuishou.password}" />

                <property name="initialSize" value="${pool.initialSize}" />
                <property name="maxActive" value="${pool.maxActive}" />
                <property name="maxIdle" value="${pool.maxIdle}"/>
                <property name="minIdle" value="${pool.minIdle}" />
                <property name="timeBetweenEvictionRunsMillis" value="${pool.timeBetweenEvictionRunsMillis}" />
                <property name="minEvictableIdleTimeMillis" value="${pool.minEvictableIdleTimeMillis}" />
                <property name="removeAbandoned" value="${pool.removeAbandoned}" />
                <property name="removeAbandonedTimeout" value="${pool.removeAbandonedTimeout}" />
                <property name="maxWait" value="${pool.maxWait}" />
                <property name="validationQuery" value="${pool.validationQuery}" />
                <property name="testOnBorrow" value="${pool.testOnBorrow}" />
                <property name="testWhileIdle" value="${pool.testWhileIdle}" />
                <property name="jdbcInterceptors" value="${pool.jdbcInterceptors}"/>
            </dataSource>
        </environment>
    </environments>

    <mappers>
        <mapper resource="ermas.xml"/>
    </mappers>

</hotwheel-mybatis>
